import { useCallback, useEffect, useMemo, useState } from 'react';
import { Pressable, StyleSheet, TextInput, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { AppScreen } from '@/components/ui/AppScreen';
import { EmptyState } from '@/components/ui/EmptyState';
import { AppCard } from '@/components/ui/AppCard';
import { AppText } from '@/components/ui/AppText';
import { AppButton } from '@/components/ui/AppButton';
import { spacing } from '@/constants/spacing';
import { useAuth } from '@/lib/auth';
import { fetchStoryReportContext, ReportReason, submitStoryReport } from '@/lib/reports';
const REASONS: { value: ReportReason; label: string }[] = [
  { value: 'inappropriate_content', label: 'محتوى غير مناسب' }, { value: 'unsafe_behavior', label: 'سلوك غير آمن' }, { value: 'harassment', label: 'مضايقة أو إساءة' }, { value: 'fraud', label: 'احتيال أو انتحال' }, { value: 'other', label: 'سبب آخر' },
];
export default function StoryReportScreen() { const { user } = useAuth(); const router = useRouter(); const { storyId } = useLocalSearchParams<{ storyId: string }>(); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState<string | null>(null); const [context, setContext] = useState<any>(null); const [reason, setReason] = useState<ReportReason | null>(null); const [details, setDetails] = useState(''); const [done, setDone] = useState(false);
  const load = useCallback(async () => { if (!user?.id || !storyId) return; setLoading(true); setError(null); try { const result = await fetchStoryReportContext(storyId, user.id); if (!result.ok) { setContext(null); setError(result.message); } else setContext(result.context); } catch { setContext(null); setError('تعذر تحميل بيانات البلاغ حالياً.'); } finally { setLoading(false); } }, [storyId, user?.id]);
  useEffect(() => { void load(); }, [load]); const canSubmit = useMemo(() => Boolean(reason) && (reason !== 'other' || Boolean(details.trim())) && !submitting, [reason, details, submitting]);
  const onSubmit = useCallback(async () => { if (!reason || !user?.id || !storyId || !canSubmit) return; setSubmitting(true); setError(null); try { const result = await submitStoryReport({ storyId, currentUserId: user.id, reason, details }); if (!result.ok) setError(result.message); else setDone(true); } catch { setError('تعذر إرسال البلاغ حالياً.'); } finally { setSubmitting(false); } }, [reason, user?.id, storyId, details, canSubmit]);
  if (!user?.id) return <AppScreen><EmptyState title="تسجيل الدخول مطلوب" description="سجّل دخولك أولاً لإرسال البلاغ." /></AppScreen>; if (!storyId) return <AppScreen><EmptyState title="رابط غير صالح" description="تعذر تحديد القصة المطلوبة." /></AppScreen>; if (loading) return <AppScreen><EmptyState title="جاري التحميل" description="نجهز لك شاشة البلاغ." /></AppScreen>;
  if (!context) return <AppScreen><View style={styles.group}><EmptyState title="تعذر فتح البلاغ" description={error ?? 'تعذر فتح الشاشة حالياً.'} /><AppButton label="رجوع" onPress={() => router.back()} /><AppButton label="إعادة المحاولة" onPress={load} variant="neutral" /></View></AppScreen>;
  if (done) return <AppScreen><View style={styles.group}><EmptyState title="تم استلام بلاغك" description="شكرًا لتعاونك. سنراجع البلاغ وفق سياسات الأمان." /><AppButton label="رجوع" onPress={() => router.back()} /></View></AppScreen>;
  return <AppScreen scrollable><View style={styles.group}><AppCard><View style={styles.group}><AppText weight="bold" style={styles.title}>الإبلاغ عن قصة</AppText><AppText weight="semibold">بلاغ ضد هذه القصة</AppText><AppText>{context.author.displayName ?? 'مستخدم'}</AppText>{context.author.username ? <AppText muted>@{context.author.username}</AppText> : null}{context.caption ? <AppText muted>النص: {context.caption}</AppText> : <AppText muted>القصة بدون نص.</AppText>}</View></AppCard><AppCard><View style={styles.group}><AppText weight="semibold">سبب البلاغ</AppText>{REASONS.map((item) => <Pressable key={item.value} onPress={() => setReason(item.value)} style={[styles.reason, reason === item.value && styles.reasonSelected]}><AppText>{item.label}</AppText></Pressable>)}</View></AppCard><AppCard><View style={styles.group}><AppText weight="semibold">تفاصيل إضافية</AppText><TextInput multiline value={details} onChangeText={setDetails} style={styles.input} placeholder="اشرح المشكلة باختصار" textAlign="right" />{reason === 'other' ? <AppText muted>هذا الحقل مطلوب عند اختيار "سبب آخر".</AppText> : null}</View></AppCard>{!!error ? <AppCard><AppText muted>{error}</AppText></AppCard> : null}<AppButton label={submitting ? 'جاري إرسال البلاغ...' : 'إرسال البلاغ'} disabled={!canSubmit} onPress={onSubmit} /></View></AppScreen>; }
const styles = StyleSheet.create({ group: { gap: spacing.sm }, title: { fontSize: 24 }, reason: { borderWidth: 1, borderColor: '#ddd', borderRadius: 10, padding: 10 }, reasonSelected: { backgroundColor: '#f5f5f5', borderColor: '#333' }, input: { borderWidth: 1, borderColor: '#ddd', borderRadius: 10, minHeight: 100, padding: 12, textAlignVertical: 'top' } });
