import { supabase } from '@/lib/supabase/client';

export type ReportReason = 'misleading_item' | 'inappropriate_content' | 'spam_offer' | 'unsafe_behavior' | 'no_show' | 'harassment' | 'fraud' | 'other';

type ReportContextReason = 'not_found' | 'unauthorized' | 'unknown';
type ParticipantSummary = { id: string; displayName: string | null; username: string | null; avatarUrl: string | null };
export type DealReportContext = { dealId: string; reporterId: string; reportedUser: ParticipantSummary };
export type UserReportContext = { reportedUser: ParticipantSummary };
export type ItemReportContext = { itemId: string; title: string; owner: ParticipantSummary };
export type StoryReportContext = { storyId: string; author: ParticipantSummary; caption: string | null };
const ALLOWED_REASONS: ReportReason[] = ['misleading_item','inappropriate_content','spam_offer','unsafe_behavior','no_show','harassment','fraud','other'];

async function fetchProfile(userId: string): Promise<ParticipantSummary | null> { const { data, error } = await supabase.from('profiles').select('id,display_name,username,avatar_url').eq('id', userId).maybeSingle(); if (error || !data) return null; return { id: data.id as string, displayName: (data.display_name as string | null) ?? null, username: (data.username as string | null) ?? null, avatarUrl: (data.avatar_url as string | null) ?? null }; }

export async function fetchDealReportContext(dealId: string, currentUserId: string) { try { const { data: deal, error } = await supabase.from('swap_deals').select('id,requester_id,offerer_id').eq('id', dealId).maybeSingle(); if (error) throw error; if (!deal) return { ok: false as const, reason: 'not_found' as const, message: 'الصفقة غير موجودة.' }; const requesterId = deal.requester_id as string; const offererId = deal.offerer_id as string; if (currentUserId !== requesterId && currentUserId !== offererId) return { ok: false as const, reason: 'unauthorized' as const, message: 'غير مسموح لك بإرسال بلاغ من هذه الصفقة.' }; const reportedUserId = currentUserId === requesterId ? offererId : requesterId; const reportedUser = await fetchProfile(reportedUserId); if (!reportedUser) return { ok: false as const, reason: 'unknown' as const, message: 'تعذر تحميل بيانات الطرف الآخر.' }; return { ok: true as const, context: { dealId, reporterId: currentUserId, reportedUser } }; } catch { return { ok: false as const, reason: 'unknown' as const, message: 'تعذر تجهيز شاشة البلاغ حالياً.' }; } }

async function insertReport(payload: any) { const { error } = await supabase.from('reports').insert(payload); if (error?.code === '42501') return { ok: false as const, reason: 'unauthorized' as const, message: 'غير مسموح لك بإرسال هذا البلاغ.' }; if (error) return { ok: false as const, reason: 'unknown' as const, message: 'تعذر إرسال البلاغ حالياً.' }; return { ok: true as const, message: 'تم استلام البلاغ.' }; }

export async function submitDealReport(input: { dealId: string; currentUserId: string; reason: ReportReason; details?: string }) { if (!ALLOWED_REASONS.includes(input.reason)) return { ok: false as const, reason: 'invalid_reason' as const, message: 'سبب البلاغ غير صالح.' }; const c = await fetchDealReportContext(input.dealId, input.currentUserId); if (!c.ok) return c; return insertReport({ reporter_id: input.currentUserId, reported_user_id: c.context.reportedUser.id, deal_id: input.dealId, reason: input.reason, details: input.details?.trim() || null, item_id: null, offer_id: null, deal_message_id: null, story_id: null }); }

export async function fetchUserReportContext(userId: string, currentUserId: string) { if (userId === currentUserId) return { ok: false as const, reason: 'unauthorized' as const, message: 'لا يمكنك الإبلاغ عن نفسك.' }; const p = await fetchProfile(userId); if (!p) return { ok: false as const, reason: 'not_found' as const, message: 'المستخدم غير موجود.' }; return { ok: true as const, context: { reportedUser: p } }; }
export async function submitUserReport(input: { reportedUserId: string; currentUserId: string; reason: ReportReason; details?: string }) { if (!ALLOWED_REASONS.includes(input.reason)) return { ok: false as const, reason: 'invalid_reason' as const, message: 'سبب البلاغ غير صالح.' }; const c = await fetchUserReportContext(input.reportedUserId, input.currentUserId); if (!c.ok) return c; return insertReport({ reporter_id: input.currentUserId, reported_user_id: input.reportedUserId, reason: input.reason, details: input.details?.trim() || null, item_id: null, offer_id: null, deal_id: null, deal_message_id: null, story_id: null }); }
export async function fetchItemReportContext(itemId: string, _currentUserId: string) { const { data, error } = await supabase.from('items').select('id,title,owner_id,status').eq('id', itemId).maybeSingle(); if (error) throw error; if (!data) return { ok: false as const, reason: 'not_found' as const, message: 'العنصر غير موجود.' }; const owner = await fetchProfile(data.owner_id as string); if (!owner) return { ok: false as const, reason: 'unknown' as const, message: 'تعذر تحميل بيانات صاحب العنصر.' }; return { ok: true as const, context: { itemId, title: ((data.title as string | null)?.trim() || 'عنصر بدون عنوان'), owner } }; }
export async function submitItemReport(input: { itemId: string; currentUserId: string; reason: ReportReason; details?: string }) { if (!ALLOWED_REASONS.includes(input.reason)) return { ok: false as const, reason: 'invalid_reason' as const, message: 'سبب البلاغ غير صالح.' }; const c = await fetchItemReportContext(input.itemId, input.currentUserId); if (!c.ok) return c; return insertReport({ reporter_id: input.currentUserId, reported_user_id: c.context.owner.id, item_id: input.itemId, reason: input.reason, details: input.details?.trim() || null, offer_id: null, deal_id: null, deal_message_id: null, story_id: null }); }
export async function fetchStoryReportContext(storyId: string, currentUserId: string) { const { data, error } = await supabase.from('stories').select('id,user_id,caption,expires_at').eq('id', storyId).maybeSingle(); if (error) throw error; if (!data) return { ok: false as const, reason: 'not_found' as const, message: 'القصة غير موجودة.' }; if ((data.user_id as string) === currentUserId) return { ok: false as const, reason: 'unauthorized' as const, message: 'لا يمكنك الإبلاغ عن قصتك.' }; const author = await fetchProfile(data.user_id as string); if (!author) return { ok: false as const, reason: 'unknown' as const, message: 'تعذر تحميل بيانات صاحب القصة.' }; return { ok: true as const, context: { storyId, author, caption: (data.caption as string | null) ?? null } }; }
export async function submitStoryReport(input: { storyId: string; currentUserId: string; reason: ReportReason; details?: string }) { if (!ALLOWED_REASONS.includes(input.reason)) return { ok: false as const, reason: 'invalid_reason' as const, message: 'سبب البلاغ غير صالح.' }; const c = await fetchStoryReportContext(input.storyId, input.currentUserId); if (!c.ok) return c; return insertReport({ reporter_id: input.currentUserId, reported_user_id: c.context.author.id, story_id: input.storyId, reason: input.reason, details: input.details?.trim() || null, item_id: null, offer_id: null, deal_id: null, deal_message_id: null }); }
