import { useCallback, useEffect, useMemo, useState } from 'react';
import { Pressable, StyleSheet, TextInput, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { AppScreen } from '@/components/ui/AppScreen';
import { EmptyState } from '@/components/ui/EmptyState';
import { AppCard } from '@/components/ui/AppCard';
import { AppText } from '@/components/ui/AppText';
import { AppButton } from '@/components/ui/AppButton';
import { spacing } from '@/constants/spacing';
import { useAuth } from '@/lib/auth';
import { ExistingDealReview, fetchDealReviewContext, submitDealReview } from '@/lib/reviews';

export default function DealReviewScreen() { /* trimmed for brevity in tool? no must full */
  const { user } = useAuth(); const router = useRouter(); const { dealId } = useLocalSearchParams<{ dealId: string }>();
  const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState<string | null>(null); const [reason, setReason] = useState<string | null>(null); const [context, setContext] = useState<any>(null);
  const [rating, setRating] = useState<number | null>(null); const [comment, setComment] = useState(''); const [clearDescription, setClearDescription] = useState(false); const [goodCommunication, setGoodCommunication] = useState(false); const [onTime, setOnTime] = useState(false); const [respectfulSwapper, setRespectfulSwapper] = useState(false); const [done, setDone] = useState(false);
  const load = useCallback(async () => { if (!user?.id || !dealId) return; setLoading(true); setError(null); setReason(null); try { const result = await fetchDealReviewContext(dealId, user.id); if (!result.ok) { setContext(null); setReason(result.reason); setError(result.message); } else setContext(result.context); } catch { setError('تعذر تحميل بيانات التقييم حالياً.'); setReason('unknown'); } finally { setLoading(false); } }, [dealId, user?.id]);
  useEffect(() => { load(); }, [load]);
  const trustTags = useMemo(() => [ { key: 'clearDescription', label: 'الوصف كان واضح', value: clearDescription, set: setClearDescription }, { key: 'goodCommunication', label: 'التواصل كان جيد', value: goodCommunication, set: setGoodCommunication }, { key: 'onTime', label: 'ملتزم بالميعاد', value: onTime, set: setOnTime }, { key: 'respectfulSwapper', label: 'محترم في التبديل', value: respectfulSwapper, set: setRespectfulSwapper } ], [clearDescription, goodCommunication, onTime, respectfulSwapper]);
  const existingReview = context?.existingReview as ExistingDealReview | null;
  const onSubmit = useCallback(async () => { if (!user?.id || !dealId || !rating || submitting) return; setSubmitting(true); setError(null); try { const result = await submitDealReview({ dealId, currentUserId: user.id, rating, comment, clearDescription, goodCommunication, onTime, respectfulSwapper }); if (!result.ok) { setError(result.message); if (result.reason === 'duplicate') await load(); } else setDone(true); } catch { setError('تعذر إرسال التقييم حالياً.'); } finally { setSubmitting(false); } }, [user?.id, dealId, rating, comment, clearDescription, goodCommunication, onTime, respectfulSwapper, submitting, load]);
  if (!user?.id) return <AppScreen><EmptyState title="تسجيل الدخول مطلوب" description="سجّل دخولك أولاً لإرسال تقييم الصفقة." /></AppScreen>;
  if (!dealId) return <AppScreen><EmptyState title="رابط غير صالح" description="تعذر تحديد الصفقة المطلوبة." /></AppScreen>;
  if (loading) return <AppScreen><EmptyState title="جاري التحميل" description="نجهز لك شاشة التقييم." /></AppScreen>;
  if (reason && !context) return <AppScreen><View style={styles.group}><EmptyState title="تعذر فتح التقييم" description={error ?? 'تعذر فتح شاشة التقييم حالياً.'} /><AppButton label="الرجوع للصفقة" onPress={() => router.push(`/deal/${dealId}`)} /><AppButton label="إعادة المحاولة" onPress={load} variant="neutral" /></View></AppScreen>;
  if (done) return <AppScreen><View style={styles.group}><EmptyState title="تم إرسال تقييمك" description="شكرًا لك. مساهمتك تساعدنا نحسّن تجربة المقايضة للجميع." /><AppButton label="الرجوع للصفقة" onPress={() => router.push(`/deal/${dealId}`)} /></View></AppScreen>;
  if (existingReview) return <AppScreen><View style={styles.group}><AppCard><View style={styles.group}><AppText weight="bold" style={styles.title}>تم تسجيل تقييمك</AppText><AppText>التقييم: {existingReview.rating} / 5</AppText>{existingReview.clearDescription ? <AppText>• الوصف كان واضح</AppText> : null}{existingReview.goodCommunication ? <AppText>• التواصل كان جيد</AppText> : null}{existingReview.onTime ? <AppText>• ملتزم بالميعاد</AppText> : null}{existingReview.respectfulSwapper ? <AppText>• محترم في التبديل</AppText> : null}{existingReview.comment ? <AppText muted>{existingReview.comment}</AppText> : null}</View></AppCard><AppButton label="الرجوع للصفقة" onPress={() => router.push(`/deal/${dealId}`)} /></View></AppScreen>;
  return <AppScreen scrollable><View style={styles.group}><AppCard><View style={styles.group}><AppText weight="bold" style={styles.title}>تقييم المقايضة</AppText><AppText weight="semibold">أنت بتقيّم:</AppText><AppText>{context.reviewee.displayName ?? 'مستخدم'}</AppText>{context.reviewee.username ? <AppText muted>@{context.reviewee.username}</AppText> : null}</View></AppCard><AppCard><View style={styles.group}><AppText weight="semibold">التقييم العام</AppText><View style={styles.row}>{[1,2,3,4,5].map((value) => <Pressable key={value} onPress={() => setRating(value)} style={[styles.chip, rating === value && styles.chipSelected]}><AppText style={rating === value ? styles.chipTextSelected : undefined}>{value}</AppText></Pressable>)}</View></View></AppCard><AppCard><View style={styles.group}><AppText weight="semibold">تفاصيل الثقة</AppText>{trustTags.map((tag) => <Pressable key={tag.key} onPress={() => tag.set(!tag.value)} style={[styles.toggle, tag.value && styles.toggleOn]}><AppText>{tag.label}</AppText></Pressable>)}</View></AppCard><AppCard><View style={styles.group}><AppText weight="semibold">ملاحظة إضافية (اختياري)</AppText><TextInput multiline value={comment} onChangeText={setComment} style={styles.input} placeholder="اكتب ملاحظة قصيرة عن التجربة (اختياري)" textAlign="right" /></View></AppCard>{!!error ? <AppCard><AppText muted>{error}</AppText></AppCard> : null}<AppButton label={submitting ? 'جاري إرسال التقييم...' : 'إرسال التقييم'} disabled={!rating || submitting} onPress={onSubmit} /></View></AppScreen>;
}

const styles = StyleSheet.create({ group: { gap: spacing.sm }, title: { fontSize: 24 }, row: { flexDirection: 'row-reverse', flexWrap: 'wrap', gap: spacing.xs }, chip: { borderWidth: 1, borderColor: '#ddd', borderRadius: 10, paddingVertical: 8, paddingHorizontal: 14 }, chipSelected: { backgroundColor: '#0f7b44', borderColor: '#0f7b44' }, chipTextSelected: { color: '#fff' }, toggle: { borderWidth: 1, borderColor: '#ddd', borderRadius: 10, padding: 10 }, toggleOn: { backgroundColor: '#e7f7ee', borderColor: '#8bd3a8' }, input: { borderWidth: 1, borderColor: '#ddd', borderRadius: 10, minHeight: 100, padding: 12, textAlignVertical: 'top' } });
